### ISSUE TITLE
Nid should be long instead of int

### ISSUE THREAD

**Issue by jnguyennova** [snap-stanford/snap#111]
In Infomap, for example, the Nid is an integer value, making it unsuitable to run analysis on very large number, such as Twitter ids, etc. Nid should be long or string.

**Comment by roks** [comment]
Use LoadEdgeListStr() to load graphs that have long ids and require strings: 
http://snap.stanford.edu/snap/doc/snapuser-ref/d3/d73/namespaceTSnap.html#a1e0d886b4ba411b8e3bc4a31a6a06af4

If your graph has more than 1.5 billion nodes, use a 64-bit version of SNAP in repository:
https://github.com/snap-stanford/snap-dev-64
