### ISSUE TITLE
How I can read the bigclam output?

### ISSUE THREAD

**Issue by ernaneluis** [snap-stanford/snap#114]
for instance running this command:
`bigclam  -i:bigclam-graph.txt -o:bigclam-out2 -c:2`

I get a txt file:  
`bigclam-out2cmtyvv.txt`

> Graph: 34979 Nodes 54382 Edges

with the values:

`22329	9	13213	790	19295	1441	13835	7121	26737	23204	19331	34747...	`

values separated by "\t"
How I read this??

**Comment by roks** [comment]
Each line represents one community, each value is a member node of that community.
