### ISSUE TITLE
running Centrality example with Twitter Dataset

### ISSUE THREAD

**Issue by AhmadSawalhah** [snap-stanford/snap#119]
I am trying to run Centrality example, using Twitter data set.
It gives me error on this line of code (centr.h)
TFltV PRankV(MxId+1); 
the error is : can't allocate memory.

when debugging, I found that the MxId is 9-digit number, because the node id in  Twitter data set is large
How Can I overcome this problem please?
I am using Windows 64, with .Net64
thanks

**Comment by roks** [comment]
Use LoadEdgeListStr(), which maps string ids to integer ids.
