### ISSUE TITLE
support multilayer networks

### ISSUE THREAD

**Issue by rafapereirabr** [snap-stanford/snap#123]
It would be great if the snap library could support multilayer networks. Is there any plans in this direction?

For example, other libraries that support multilayer networks include [graph-tool](https://graph-tool.skewed.de/static/doc/demos/inference/inference.html#layered-networks) and [MuxViz](https://github.com/manlius/muxViz), the latter is developed in `R`

**Comment by roks** [comment]
SNAP supports multi-modal networks with TMMNet, which are a generalization of multilayer networks. An alternative is to use TNEANet and encode the edges in attributes. There are currently no plans to have a separate class for multilayer networks.
