### ISSUE TITLE
Incorrect value lookup in NIdDistH

### ISSUE THREAD

**Issue by aaronaquino** [snap-stanford/snap#127]
In these lines, we should be looking up values in `NIdDistH` using the `GetDat()` function, which accepts a key. Currently the function uses `[]` notation, which incorrectly assumes we are looking up by key ID.

https://github.com/snap-stanford/snap/blob/b9e50cb55218d1007c64bece3f56d4c3941dc8c9/snap-core/centr.cpp#L690-L691

**Comment by roks** [comment]
Thank you for the report! This has been fixed.
