### ISSUE TITLE
SNAP R integration

### ISSUE THREAD

**Issue by thomasp85** [snap-stanford/snap#132]
This is both an FYI and a question of license and attribution

I'm planning on building an Rcpp integration of SNAP that would allow R developers to access the SNAP C++ API without including SNAP directly in their own packages. Similar efforts have been done with e.g. the linear algebra libraries [Armadillo](https://github.com/RcppCore/RcppArmadillo) and [Eigen](https://github.com/RcppCore/RcppEigen).

I generally release my work under MIT - will that be compatible with SNAPs BSD licence?

Further, the SNAP team should receive due attribution for their work - how  would you like to be recognised? as a team or as individuals (and who should then be included)?

best
Thomas

**Comment by roks** [comment]
Hi Thomas,

Your plan sounds great, thank you! Your chosen license is compatible with ours. You can attribute our work to Stanford SNAP and provide a URL: snap.stanford.edu.

If there is anything else we can help please let us know.

Best,
Rok

**Comment by thomasp85** [comment]
Fantastic - I might have questions once I get down to the nitty gritty of getting SNAP to play nice with R's toolchain, but I'll see how far I can get before bothering you :-)

Further, this has no timeframe and I'm a man of many projects so don't expect a swift MVP :-)

**Comment by roks** [comment]
Very good!
