### ISSUE TITLE
CESNA community Detection input format

### ISSUE THREAD

**Issue by shashankg7** [snap-stanford/snap#135]
Hi,

I am trying to run the "CESNA" community detection algorithm on my dataset. Howerver, I am not able to get the input format for passing the node features to the algorithm. 

The example file which is given is not clear. Could you please provide/explain the schema for node attributes file. 

Thanks in advance!

**Comment by roks** [comment]
The edges file, 1912.edges, provides one edge per line, the first column is the source edge, the second column is the destination edge. The node attribute file, 1912.nodefeat, provides nodes attributes, the first column is the node id, the second column is the feature value. The node feature names file, 1912.nodefeatnames, provides a mapping from feature values to feature text, the first column is feature value, the second is a text of all the features.
