### ISSUE TITLE
Ask for example to load large network dataset (or multiple *.edges files)

### ISSUE THREAD

**Issue by nie93** [snap-stanford/snap#141]
Hi all,

I am working on a community detection case which needs to load multiple/all `*.edges` files at one time, imported from SNAP dataset, such as Twitter-ego. I check on the `cesna.cpp`, but it only uses one file `1912.edges` when loading. Is there anyone can provide an example on edges partition files loading?

Appreciate it!
Jack

**Comment by roks** [comment]
As you observed, CESNA requires one input file. You need to merge your multiple files into one input file.
