### ISSUE TITLE
install R-tensorflow on mac

### ISSUE THREAD

**Issue by Mayssoune** [snap-stanford/snap#143]
Hi,
I got this error When I try to run my code, how can I use R environment with anacondaenv? 

Error: Python module keras was not found.

Detected Python configuration:

python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Feb  7 2017, 00:08:15)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.0
keras:          [NOT FOUND]

python versions found: 
 /anaconda2/envs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python3

**Comment by roks** [comment]
From the description above, this issue does not seem to be connected to this repository. If it is, please provide more details.
