### ISSUE TITLE
Error trying to estimate community number

### ISSUE THREAD

**Issue by oiwilliam** [snap-stanford/snap#182]
I'm trying to estimate the -c parameter for my graph. For that, I've used the -mc and -xc parameters, but the system halts with "killed" error. Independently of the parameters specified in the -mc and -xc, when I use -c:-1, the application increases the memory consumption till there are no more memory and crashes down. Any Idea? 

Command used:
``` ./bigclam -mc:10 -xc:20 -nt:7 -nc:1 -o:out.txt i:input.csv  -c:-1 ```
Output:
```
ragm. build: 17:25:50, Oct 13 2019. Time: 12:52:05 [Oct 13 2019]
================================================================
Output Graph data prefix (-o:)=out.txt
Input edgelist file name (-i:)=input.csv
Input file name for node names (Node ID, Node label)  (-l:)=
The number of communities to detect (-1: detect automatically) (-c:)=-1
Minimum number of communities to try (-mc:)=10
Maximum number of communities to try (-xc:)=20
How many trials for the number of communities (-nc:)=1
Number of threads for parallelization (-nt:)=7
Alpha for backtracking line search (-sa:)=0.05
Beta for backtracking line search (-sb:)=0.3
Graph: 190608 Nodes 2436844 Edges
finding number of communities
generating hold out set
holding out 243684 edges...
243684 Edges hold out
holding out 243684 edges...
243684 Edges hold out
Killed
```

**Comment by roks** [comment]
It seems that there is insufficient RAM in the computer for this graph. Try to run the program on a machine with more RAM.

**Comment by oiwilliam** [comment]
It is using 64 Gb of RAM for this network. It really supposed to use so much memory? I’m able to use many communities detections algorithms in this machine, so I think it is strange...
