### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by Mrfangfang** [snap-stanford/snap#187]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/snap.py", line 15, in <module>
    import _snap
ImportError: dlopen(/Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/_snap.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/_snap.so
  Reason: image not found

**Comment by damicoedoardo** [comment]
>>> import snap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/rsys/lib/python3.7/site-packages/snap.py", line 15, in <module>
    import _snap
ImportError: dlopen(/opt/miniconda3/envs/rsys/lib/python3.7/site-packages/_snap.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /opt/miniconda3/envs/rsys/lib/python3.7/site-packages/_snap.so
  Reason: image not found


same here.

**Comment by Lucaslhm** [comment]
> Traceback (most recent call last):
> File "", line 1, in
> File "/Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/snap.py", line 15, in
> import _snap
> ImportError: dlopen(/Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/_snap.so, 2): Library not loaded: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
> Referenced from: /Users/mrfang/Downloads/snap-stanford-5.0.0-5.0-macosx10.14.4-x64-py3.7/_snap.so
> Reason: image not found

Happened here as well.

**Comment by anbhat87** [comment]
Same here, anybody able to resolve this issue?

**Comment by opengit** [comment]
Same problem.

**Comment by yangjingla** [comment]
same problem...

**Comment by sgGoel** [comment]
same here

**Comment by roks** [comment]
What is your python version? Where did you obtained it from - brew, conda, python.org, elsewhere? How did you install snap.py - pip, conda, setup.py?

**Comment by sgGoel** [comment]
Python 3.7.8 (the local version where I've installed snap-stanford). Python was obtained via pyenv, which was obtained via brew
I ran pip install snap-stanford in a virtual env (test2)
snap-stanford in /Users/swati/.pyenv/versions/3.7.8/envs/test2/lib/python3.7/site-packages (5.0.0)
I'm getting the same error regarding _snap.so

**Comment by finalfire** [comment]
Hello there, I'm getting the same error.

**Comment by jasonppy** [comment]
Same error. I installed it using pip, my python version is 3.7.4

**Comment by roks** [comment]
Snap.py 6.0.0 has been released. Please check it out and let me know if there is still a problem. Use pip to install it.

**Comment by a-n-622** [comment]
Hey @roks the issue still persists for me. I am using colab and snap, but it ain't working there. 
Specifically, I am using 'PlotShortPathDistr' and 'PlotOutDegDistr'. For both of the cases, the '.png' file is missing, while the other two (.plt and .tab) files are being created. Please have a look.

**Comment by roks** [comment]
Make sure that Gnuplot is installed: http://snap.stanford.edu/snappy/index.html#system
