### ISSUE TITLE
node2vec gets killed while running on youtube and flickr dataset

### ISSUE THREAD

**Issue by sarthak-chakraborty** [snap-stanford/snap#188]
Whenever I try to to run node2vec on youtube and flickr dataset, it gets killed. However, on smaller dataset like the BlogCatalog, it runs perfectly. 

An algorithmic framework for representational learning on graphs. [Jan 19 2020]
================================================================================
Input graph path (-i:)=graph/youtube.txt
Output graph path (-o:)=emb/youtube.emb
Number of dimensions. Default is 128 (-d:)=128
Length of walk per source. Default is 80 (-l:)=80
Number of walks per source. Default is 10 (-r:)=10
Context size for optimization. Default is 10 (-k:)=10
Number of epochs in SGD. Default is 1 (-e:)=1
Return hyperparameter. Default is 1 (-p:)=1
Inout hyperparameter. Default is 1 (-q:)=1
Verbose output. (-v)=YES
Graph is directed. (-dr)=YES
Graph is weighted. (-w)=NO
Output random walks instead of embeddings. (-ow)=NO
Read 4945382 lines from graph/youtube.txt
Killed

Where can the issue lie?

**Comment by dhimmel** [comment]
I encountered the `Killed` message and reran the process on a system with more memory and no longer got the error.
