### ISSUE TITLE
Install motifcluster: /usr/bin/ld: cannot find -larpack

### ISSUE THREAD

**Issue by LleytonLi** [snap-stanford/snap#201]
snap-master/examples/motifcluster: when use 'make' to build the binary, it returns an error '/usr/bin/ld: cannot find -larpack'. Does anyone know what might be the cause of it? Thanks!

**Comment by roks** [comment]
ARPACK is a third party package. You can get it here: https://www.caam.rice.edu/software/ARPACK/download.html

**Comment by manishshah1698** [comment]
The link provided doesn't work anymore. Can you share the updated link?

**Comment by roks** [comment]
Yes, it seems that the website for the ARPACK download has been recently changed and that the link is not active anymore. The package installation will depend on your OS. I suggest that you search on Google for the best method for your platform. We used "brew install arpack" on macOS in the past.
