### ISSUE TITLE
Can't compile SNAP c++ source code!

### ISSUE THREAD

**Issue by mhdmyz** [snap-stanford/snap#209]
I want to compile SNAP (Stanford Network Analysis Project) c++ source code using terminal on mac by running the make all command and I'm getting the following error:

ld: symbol(s) not found for architecture x86_64

Initially I was getting this error:

clang: error: unsupported option '-fopenmp'

but I found that I should replace the g++ in the Makefile.config with gcc-10 which I installed using the homebrew and now I'm getting the architecture error!

I'm on mac os Big Sur 11.0.1 and everything is up to date! Does anyone have any clue?

<img width="567" alt="Screen Shot 1399-09-10 at 03 21 51" src="https://user-images.githubusercontent.com/47456155/100764750-ed923a00-340b-11eb-8903-8d28cb65c069.png">
<img width="563" alt="Screen Shot 1399-09-10 at 03 31 20" src="https://user-images.githubusercontent.com/47456155/100764753-eff49400-340b-11eb-92f1-151e56b3a6ea.png">
<img width="445" alt="Screen Shot 1399-09-10 at 03 33 16" src="https://user-images.githubusercontent.com/47456155/100764757-f08d2a80-340b-11eb-98bb-05277e9a49dd.png">

**Comment by lynochka** [comment]
I don't think I have the same error but i could not compile the code either: 
>mingw32-make all
C:/MinGW/bin/mingw32-make -C snap-core
process_begin: CreateProcess(NULL, uname, ...) failed.
process_begin: CreateProcess(NULL, uname -o, ...) failed.
mingw32-make[1]: Entering directory 'C:/repos/snap/snap-core'
cc -c  Snap.cpp -I../glib-core
process_begin: CreateProcess(NULL, cc -c Snap.cpp -I../glib-core, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:13: recipe for target 'Snap.o' failed
mingw32-make[1]: *** [Snap.o] Error 2
mingw32-make[1]: Leaving directory 'C:/repos/snap/snap-core'
Makefile:10: recipe for target 'MakeAll' failed
mingw32-make: *** [MakeAll] Error 2

**Comment by roks** [comment]
This seems like an error with the compiler installation. The compiler does not even start.
