### ISSUE TITLE
Unable to install in either Windows(using Cygwin make) or Ubuntu

### ISSUE THREAD

**Issue by sumandutta8877** [snap-stanford/snap#216]
Snap could not be installed in any OS.

The Makefile in GitHub version is only giving errors in both Ubuntu & Windows.

The Windows executable file available on Stanford's website is corrupted with viruses, and the Ubuntu Installation has no make file in it.

**Comment by roks** [comment]
Can you please provide more details on which executable file is corrupted and a description of errors on Ubuntu?

**Comment by roks** [comment]
There must be some issues with your installation. I just successfully unzipped the file above and completed 'make' on Ubuntu.
