### ISSUE TITLE
Bio snap works + code?

### ISSUE THREAD

**Issue by ddofer** [snap-stanford/snap#229]
Can someone point me towards some code working with and integrating biosnap? It's a bit unclear to me how to get started (python +- graph methods or tabular +- graph NNs). Also, it's a bit unclear if decagon overlaps with some of the other networks in the repo (e.g. DD). 
Any example code/repos available? Thanks!

**Comment by roks** [comment]
Additional code and information is available on our Projects pages: http://snap.stanford.edu/
