### ISSUE TITLE
Execution stopped: !IsNode(NId) [Reason:'NodeId 1 already exists']

### ISSUE THREAD

**Issue by atabati** [snap-stanford/snap#39]
I have a very simple code that the AddNode function creates the following error for me:

**\* Error: Execution stopped: !IsNode(NId) [Reason:'NodeId 1 already exists'], file graph.cpp, line 12

The problematic line :
if (!Graph->IsNode(srcNId)) Graph->AddNode(srcNId);

This totally fine by compiling under Windows. But, I must compile my program on a cluster that works with linux (sharcnet.ca), unfortunately SNAP does not fit with their system, there are several problems I found out. For example, using just GenGrid function gave me segmentation fault. 

This is the whole code:

PUNGraph Graph = TUNGraph::New();
TSsParser parser("grid.txt", ssfWhiteSep, true, true, true);
while (parser.Next()) {
    const int srcNId = parser.GetInt(0);
    const int dstNId = parser.GetInt(1);
    if (!Graph->IsNode(srcNId)) Graph->AddNode(srcNId); 
    if (!Graph->IsNode(dstNId)) Graph->AddNode(dstNId);
    if (!Graph->IsEdge(srcNId, dstNId)) 
        Graph->AddEdge(srcNId, dstNId);
}

Thanks in advance.

**Comment by myth17** [comment]
At present I am facing the same issue in SNAP. Any suggestions on resolving it ?
