### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by radiative** [snap-stanford/snap#59]
build (make all) fails:
make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C snap-core
g++ -c -std=c++98 -Wall -O3 -DNDEBUG -DNOMP Snap.cpp -I../glib-core
Snap.cpp:29:10: fatal error: 'triad.cpp' file not found
#include "triad.cpp"         // triad calculations
         ^
1 error generated.
make[1]: *** [Snap.o] Error 1
make: *** [MakeAll] Error 2

**Comment by roks** [comment]
triad.cpp has been added. Please try again.
