### ISSUE TITLE
import snap Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by xunlao** [snap-stanford/snap#62]
```python
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import snap
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```
============================================
Please help...............
error log see below:

Process:               Python [11381]
Path:                  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        bash [11371]
Responsible:           iTerm [7379]
User ID:               501

Date/Time:             2015-10-16 20:26:42.407 -0500
OS Version:            Mac OS X 10.11 (15A284)
Report Version:        11
Anonymous UUID:        D5054451-BC61-CA61-9BF6-89966A16F02C

Sleep/Wake UUID:       3BF6D8EC-E1CA-4FBD-9843-44EF0D90D3C8

Time Awake Since Boot: 11000 seconds
Time Since Wake:       1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8894b0ae __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff969c7500 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8cef937b abort + 129
3   org.python.python             	0x0000000105a69ce2 Py_FatalError + 49
4   org.python.python             	0x0000000105a691f0 PyThreadState_Get + 28
5   org.python.python             	0x0000000105a6603a Py_InitModule4_64 + 62
6   _snap.so                      	0x000000010443697f init_snap + 559
7   org.python.python             	0x00000001000deba1 _PyImport_LoadDynamicModule + 177
8   org.python.python             	0x00000001000dcc58 imp_load_module + 184
9   org.python.python             	0x00000001000c357d PyEval_EvalFrameEx + 24829
10  org.python.python             	0x00000001000c467e PyEval_EvalFrameEx + 29182
11  org.python.python             	0x00000001000c58e3 PyEval_EvalCodeEx + 2115
12  org.python.python             	0x00000001000c5a06 PyEval_EvalCode + 54
13  org.python.python             	0x00000001000da0a0 PyImport_ExecCodeModuleEx + 208
14  org.python.python             	0x00000001000db2a2 load_source_module + 626
15  org.python.python             	0x00000001000dd28b import_submodule + 315
16  org.python.python             	0x00000001000dd73a load_next + 234
17  org.python.python             	0x00000001000dda30 PyImport_ImportModuleLevel + 336
18  org.python.python             	0x00000001000bafe3 builtin___import__ + 131
19  org.python.python             	0x000000010000c612 PyObject_Call + 98
20  org.python.python             	0x00000001000bc1c7 PyEval_CallObjectWithKeywords + 87
21  org.python.python             	0x00000001000c0432 PyEval_EvalFrameEx + 12210
22  org.python.python             	0x00000001000c58e3 PyEval_EvalCodeEx + 2115
23  org.python.python             	0x00000001000c5a06 PyEval_EvalCode + 54
24  org.python.python             	0x00000001000e9f4c PyRun_InteractiveOneFlags + 380
25  org.python.python             	0x00000001000ea1ae PyRun_InteractiveLoopFlags + 78
26  org.python.python             	0x00000001000ea9c1 PyRun_AnyFileExFlags + 161
27  org.python.python             	0x000000010010187d Py_Main + 3101
28  org.python.python             	0x0000000100000f14 0x100000000 + 3860

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff5fbfe638  rdx: 0x0000000000000000
  rdi: 0x0000000000000a0b  rsi: 0x0000000000000006  rbp: 0x00007fff5fbfe660  rsp: 0x00007fff5fbfe638
   r8: 0x0000000000000040   r9: 0x00007fff758f91e0  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x0000000000000000  r13: 0x0000000105429efb  r14: 0x00007fff76e9a000  r15: 0x00000001036355d4
  rip: 0x00007fff8894b0ae  rfl: 0x0000000000000206  cr2: 0x00007fff758f7038
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Binary Images:
       0x100000000 -        0x100000fff +org.python.python (2.7.10 - 2.7.10) <DA2FF3FB-F70D-A899-1829-4F86802713E0> /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
       0x100003000 -        0x100170fff +org.python.python (2.7.10, [c] 2001-2015 Python Software Foundation. - 2.7.10) <5E0C1150-83D5-6364-A820-E7AD67962D79> /Library/Frameworks/Python.framework/Versions/2.7/Python
       0x1002f2000 -        0x1002f4ff7 +_locale.so (???) <3C1429AD-B0EF-96BF-9E7E-2F7B48975B36> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
       0x1020f0000 -        0x1020f2ff7 +readline.so (???) <B017FDFA-C127-182D-0FDC-C89FD968CB0A> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so
       0x102240000 -        0x102294fe7 +libncursesw.5.dylib (5) <3F0079C0-01C1-3CB8-19CA-F9B49AA4F4A4> /Library/Frameworks/Python.framework/Versions/2.7/lib/libncursesw.5.dylib
       0x103680000 -        0x1055f6fe7 +_snap.so (0) <3D2FCCCC-4937-3BC0-AF45-3FAAE655B204> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_snap.so
       0x1059c8000 -        0x105ab9ff7  org.python.python (2.7.10 - 2.7.10) <5A7838D3-24D4-395B-BE96-ADD007C86E55> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
    0x7fff65a4e000 -     0x7fff65a84f5f  dyld (360.14) <DF977301-4A63-32ED-9939-1EE3122D18D4> /usr/lib/dyld
    0x7fff8576f000 -     0x7fff8579cfff  libdispatch.dylib (500.1.5) <6B38497E-9448-3433-9D6B-6223F2A99431> /usr/lib/system/libdispatch.dylib
    0x7fff85a25000 -     0x7fff85a27ff7  libsystem_configuration.dylib (801.1.1) <EB55C3D8-048D-350E-BF24-0CBD4479D51C> /usr/lib/system/libsystem_configuration.dylib
    0x7fff85c2c000 -     0x7fff85c4affb  libedit.3.dylib (43) <744915BA-9B98-3256-8DBB-5C760132623F> /usr/lib/libedit.3.dylib
    0x7fff85c4b000 -     0x7fff85c52ff7  libcompiler_rt.dylib (62) <253B36E5-572D-377D-AE99-A02CE32590E5> /usr/lib/system/libcompiler_rt.dylib
    0x7fff86670000 -     0x7fff866beff7  libstdc++.6.dylib (104.1) <77780A99-22DB-35AA-BD9E-ADB83417E4BD> /usr/lib/libstdc++.6.dylib
    0x7fff866d2000 -     0x7fff866eeff7  libsystem_malloc.dylib (67) <1B57A614-3D60-3F87-876F-7DB4AF38120F> /usr/lib/system/libsystem_malloc.dylib
    0x7fff86d02000 -     0x7fff86d03ffb  libSystem.B.dylib (1225.1.1) <E48AAE3F-370E-34AE-AECA-4CA28F211479> /usr/lib/libSystem.B.dylib
    0x7fff86f0d000 -     0x7fff8711afff  libicucore.A.dylib (551.24) <DEB70F32-DA94-323B-B6D1-03D09C8FB10C> /usr/lib/libicucore.A.dylib
    0x7fff873c0000 -     0x7fff87406ff7  libauto.dylib (186) <460B0167-C89B-37EC-823C-52F684B31C26> /usr/lib/libauto.dylib
    0x7fff8745f000 -     0x7fff878d3ff7  com.apple.CoreFoundation (6.9 - 1253) <A8A44D66-A3B2-3B5D-B75B-EC2DC968F4BD> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff878d4000 -     0x7fff87c376d7  libobjc.A.dylib (680) <7C5FAD04-2C01-3ED6-AA40-78925C12A456> /usr/lib/libobjc.A.dylib
    0x7fff87ca2000 -     0x7fff87caafef  libsystem_platform.dylib (73.1.1) <3F4D2390-E3DE-3C24-A515-95DFAC8671C4> /usr/lib/system/libsystem_platform.dylib
    0x7fff87cab000 -     0x7fff87d22fc7  libcorecrypto.dylib (334) <4E1B969F-8449-3B21-9880-51AD58E25AA6> /usr/lib/system/libcorecrypto.dylib
    0x7fff87d23000 -     0x7fff87d3afff  libsystem_asl.dylib (322) <97D794DA-8CE5-3676-AC5E-364F6D172BDA> /usr/lib/system/libsystem_asl.dylib
    0x7fff881c4000 -     0x7fff88217ff7  libc++.1.dylib (120.1) <54190E1B-EE49-3D6D-AC29-2813D7380BA5> /usr/lib/libc++.1.dylib
    0x7fff887e4000 -     0x7fff88813fc3  libsystem_m.dylib (3105) <07D50372-30ED-3B03-9FA0-0662BF8F0098> /usr/lib/system/libsystem_m.dylib
    0x7fff88934000 -     0x7fff88952fff  libsystem_kernel.dylib (3247.1.106) <7DD242A1-E2BF-39D1-8787-B174046E4F15> /usr/lib/system/libsystem_kernel.dylib
    0x7fff88960000 -     0x7fff88965ff3  libunwind.dylib (35.3) <FDA18078-A775-3BAF-A5A6-8A7B75D6AA99> /usr/lib/system/libunwind.dylib
    0x7fff89504000 -     0x7fff89504ff7  liblaunch.dylib (755.1.19) <7EC0F297-43CC-3D11-B46B-7E72E372648A> /usr/lib/system/liblaunch.dylib
    0x7fff8a6a5000 -     0x7fff8a6b6fff  libz.1.dylib (60) <43317BEA-ACA2-34C2-AF37-902AA926C83A> /usr/lib/libz.1.dylib
    0x7fff8a6f1000 -     0x7fff8a6faffb  libsystem_notify.dylib (149) <56ABC155-CB99-30A8-A8B1-C204B5615092> /usr/lib/system/libsystem_notify.dylib
    0x7fff8a98f000 -     0x7fff8a992fff  libsystem_sandbox.dylib (459.1.8) <2F36D536-482C-39EC-BAFD-72297728F0A4> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8afb6000 -     0x7fff8afb6ff7  libunc.dylib (29) <D9B0C7B1-8648-3AAC-931C-E7CD362FAA8A> /usr/lib/system/libunc.dylib
    0x7fff8b280000 -     0x7fff8b281fff  libDiagnosticMessagesClient.dylib (100) <F2D8CFCC-A00A-3675-9C01-EF0C663F2445> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8ce9b000 -     0x7fff8cf28fe7  libsystem_c.dylib (1081.1.3) <A60CE86D-1FF3-32AD-A672-C7597F884529> /usr/lib/system/libsystem_c.dylib
    0x7fff8d9bd000 -     0x7fff8d9c2ff7  libmacho.dylib (875.1) <A9EC23EC-11A0-3B4F-A8AC-B990C8267A6E> /usr/lib/system/libmacho.dylib
    0x7fff8d9c3000 -     0x7fff8d9cbfff  libcopyfile.dylib (127) <CA2602AB-E8B7-3CD8-A0C5-D86E35FDA09F> /usr/lib/system/libcopyfile.dylib
    0x7fff8e038000 -     0x7fff8e096fff  libsystem_network.dylib (582.1.4) <14ECA259-D471-3E47-A843-FF0990577893> /usr/lib/system/libsystem_network.dylib
    0x7fff8e097000 -     0x7fff8e097ff7  libkeymgr.dylib (28) <47080280-8B57-3D75-8A20-9E100864DE27> /usr/lib/system/libkeymgr.dylib
    0x7fff923a8000 -     0x7fff923acfff  libcache.dylib (75) <4948E2C8-867F-3E9D-AAE7-2F30F0B345C6> /usr/lib/system/libcache.dylib
    0x7fff925a5000 -     0x7fff925a6fff  libsystem_secinit.dylib (20) <932ED582-E80F-39DA-B0FA-F1BC5F1AD2F8> /usr/lib/system/libsystem_secinit.dylib
    0x7fff925b8000 -     0x7fff925b9ffb  libremovefile.dylib (41) <C7CFF5F2-AFFB-3C8D-BDB4-D66D50E657C0> /usr/lib/system/libremovefile.dylib
    0x7fff92851000 -     0x7fff9287afff  libc++abi.dylib (125) <F5027B46-1801-344D-BD51-2E6D188C8900> /usr/lib/libc++abi.dylib
    0x7fff92901000 -     0x7fff9292afff  libxpc.dylib (755.1.19) <3E09C275-A33B-357A-B0AB-A2DDF88EC9D5> /usr/lib/system/libxpc.dylib
    0x7fff93025000 -     0x7fff93056ff7  libncurses.5.4.dylib (46) <766F2188-F523-3FAA-AC1F-49447F09E133> /usr/lib/libncurses.5.4.dylib
    0x7fff93137000 -     0x7fff93139fff  libsystem_coreservices.dylib (19) <692631A0-1923-32CA-9BD5-044B1382FFDE> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff932c3000 -     0x7fff932ecff7  libsystem_info.dylib (476) <65D0643A-C8AE-3E8D-9F6E-E4AD823F16B2> /usr/lib/system/libsystem_info.dylib
    0x7fff95a07000 -     0x7fff95a09ff7  libquarantine.dylib (80) <1693C5FE-EA0A-3122-85EB-7950ECC7435A> /usr/lib/system/libquarantine.dylib
    0x7fff95d22000 -     0x7fff95d2afff  libsystem_networkextension.dylib (384.1.2) <4736FCC5-9DBA-31F4-AAC8-CD0A177CF502> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff9694e000 -     0x7fff96962fff  libsystem_coretls.dylib (82) <21EDACF1-D9B3-3086-9821-60EB75E7F965> /usr/lib/system/libsystem_coretls.dylib
    0x7fff96966000 -     0x7fff96967fff  libsystem_blocks.dylib (65) <1B4F1F10-823E-3781-8162-6884D14DF0D6> /usr/lib/system/libsystem_blocks.dylib
    0x7fff969c1000 -     0x7fff969caff7  libsystem_pthread.dylib (137.1.1) <1373D0F1-C6CA-364E-A6BA-8BDBD0D34670> /usr/lib/system/libsystem_pthread.dylib
    0x7fff96a45000 -     0x7fff96a56ff7  libsystem_trace.dylib (200) <E26A91EA-AD67-3FA2-A3B6-79A93DCC716E> /usr/lib/system/libsystem_trace.dylib
    0x7fff97794000 -     0x7fff97797ffb  libdyld.dylib (360.14) <F9D64D8C-4C33-3D06-B7F8-697F13292894> /usr/lib/system/libdyld.dylib
    0x7fff97798000 -     0x7fff977a3ff7  libcommonCrypto.dylib (60074) <BD1DCF19-8353-3F6A-AFFA-EBBA29A302A8> /usr/lib/system/libcommonCrypto.dylib
    0x7fff98089000 -     0x7fff98091ffb  libsystem_dnssd.dylib (624.1.2) <DB6AB206-4AD8-369D-BF57-1D246AD60582> /usr/lib/system/libsystem_dnssd.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 18946
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=140.2M resident=0K(0%) swapped_out_or_unallocated=140.2M(100%)
Writable regions: Total=60.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=60.0M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            49.7M       18 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                            4184K       57 
__LINKEDIT                        91.4M       10 
__TEXT                            48.8M       55 
__UNICODE                          552K        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                            260.5M      147

**Comment by roks** [comment]
This problem usually happens, when many pythons are installed on the system. One solution is to telete all pythons other than the one provided by Apple, like the following:
cd /usr/local/bin; 
ls -l . | grep '../Library/Frameworks/Python.framework/Versions/2.7' | awk '{print $9}' | xargs rm

Then, switch to the apple versions python using the command:
sudo port select python python27-apple
install snap.py afterwards and it will work.
