### ISSUE TITLE
Node (Edge) betweenness centrality for directed graphs ? 

### ISSUE THREAD

**Issue by python27** [snap-stanford/snap#64]
Hi, guys

Did SNAP provides algorithms for calculating betweenness centrality for _**directed graphs**_ ? 

I have found 4 related functions, but all of them only accept undirected graphs as parameters, as followings:
```
void TSnap::GetBetweennessCentr (const PUNGraph &Graph, TIntFltH &NodeBtwH, const double &NodeFrac)'
 
void TSnap::GetBetweennessCentr (const PUNGraph &Graph, TIntPrFltH &EdgeBtwH, const double &NodeFrac)
 
void TSnap::GetBetweennessCentr (const PUNGraph &Graph, TIntFltH &NodeBtwH, TIntPrFltH &EdgeBtwH, const double &NodeFrac)
 
void TSnap::GetBetweennessCentr (const PUNGraph &Graph, const TIntV &BtwNIdV, TIntFltH &NodeBtwH, const bool &DoNodeCent, TIntPrFltH &EdgeBtwH, const bool &DoEdgeCent)
```

**Comment by shubhamg31** [comment]
Hi,

I have implemented a general method for calculating betweenness centrality which works for directed graphs too in my repository but it is not yet merged with the main repo.

**Comment by roks** [comment]
We plan to merge Shubham's updates in the near future.
