### ISSUE TITLE
Finding Progression Stages in Time-evolving Event Sequences

### ISSUE THREAD

**Issue by aflaxman** [snap-stanford/snap#69]
A colleague recently showed me the WWW 2014 paper “Finding Progression Stages in Time-evolving Event Sequences” recently, and it could be just the thing I need for analyzing some health claims data.

In the paper, it says the code is available in the snap package, but I couldn’t find it in the repo (https://github.com/snap-stanford/snap-dev ).  I did find some implementation (https://github.com/m-ochi/progression_stage_model ), and it seems to work, but I’m hoping yours is faster.

Is it around here somewhere?

**Comment by profjure** [comment]
Hi!
Thanks for the question. The code can be found here:
http://infolab.stanford.edu/~crucis/code/stages-package.zip
Jure

**Comment by aflaxman** [comment]
Thanks @profjure !
