### ISSUE TITLE
TStr thread safety

### ISSUE THREAD

**Issue by chantat** [snap-stanford/snap#72]
I noticed that TStr is thread unsafe. It would be useful to have some comments warning about this. An example that I ran into is the following:

Let C be a TStr and consider these two lines running in parallel:
TStr A = C;
TStr B = C;

C.RStr->MkRef() would be run concurrently which can cause the reference count to be incorrect.

**Comment by roks** [comment]
We are aware of this limitation. We expect to address this issue no later than this summer.

**Comment by zitaoliu** [comment]
Has this issue been fixed?

**Comment by roks** [comment]
Not yet, hopefully it will be done by this summer.
